### PR TITLE
Update download.de

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by ShalokShalom** [comment]
So this repo here is just to make more work for us and confuse a little bit? :P

**Comment by dirkhh** [comment]
Not sure where you found the repo, but I sure never provide a link to it from anywhere on the website. It's also way out of sync with the current website.

I appreciate your fixes and will pull them, so don't worry.

⁣-- 
From my phone​


-------- Original Message --------

**Comment by ShalokShalom** [comment]
Thanks a lot. I googled for them. Is there any link on the homepage to the correct repo?

**Comment by dirkhh** [comment]
I don't think so. We have a link to our official GitHub account which also includes this repo.
Once I have internet on my computer again, I'll merge both of your requests (except for the "dass" :-) )

/D

⁣-- 
From my phone​


-------- Original Message --------

**Comment by dirkhh** [comment]
Ich habe den beide commits gemerged (auch nicht wirklich ein deutsches Wort):
https://github.com/Subsurface-divelog/Subsurface-website/commit/6669e4c1f1270ea468c686dd53b3ad6967550b28

**Pull request closed without merging**
